
  
name: Building Release Build
on: [push]

env:
  CARGO_TERM_COLOR: always


jobs:
    Windows:
        name: Windows Release Build
        runs-on: windows-latest
        steps:
         - name: Checkout Code
           uses: actions/checkout@v3
           
         - name: Building Windows Release Build
           run: cargo build --release
           
         - name: Upload Artifacts 
           uses: actions/upload-artifact@v3
           with:
            name: shticker_book_unwritten_win.exe
            path: target/release/shticker_book_unwritten.exe



    Linux:
        name: Linux Release Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              
            - name: Building Linux Release Build
              run: cargo build --release
              
            - name: Upload Artifacts 
              uses: actions/upload-artifact@v3
              with:
               name: shticker_book_unwritten_linux
               path: target/release/shticker_book_unwritten
               
    Mac:
        name: Mac Release Build
        runs-on: macos-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v3
            
          - name: Install Cross Compile Tools
            run: rustup target add aarch64-apple-darwin	
            
          - name: Building macOS Release Build (ARM64)
            run: cargo build --release --target aarch64-apple-darwin
          
          - name: Upload Artifacts
            uses: actions/upload-artifact@v3
            with:
               name: shticker_book_unwritten_macos_arm64
               path: target/aarch64-apple-darwin/release/shticker_book_unwritten
    Upload-Releases:
         name: Upload Release
         runs-on: ubuntu-latest
         needs: [Windows, Linux, Mac]
         steps:
         - uses: actions/download-artifact@v3
           with:
            name: my-artifact
         - name: Display structure of downloaded files
           run: ls -R
         
    
            
               
               
        
             
            
          
       
     
              

              



    
