
  
name: Building Release Build
on: [push]

env:
  CARGO_TERM_COLOR: always


jobs:
    Windows:
        name: Windows Release Build
        runs-on: windows-latest
        steps:
         - name: Checkout Code
           uses: actions/checkout@v3
           
         - name: Building Windows Release Build
           run: cargo build --release
           
         - name: Release The Build
           uses: "marvinpinto/action-automatic-releases@latest"
           with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: "latest"
              prerelease: false
              title: "Release Build"
              files: |
                 target/release/shticker_book_unwritten.exe


    Linux:
        name: Linux Release Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              
            - name: Building Linux Release Build
              run: cargo build --release
              
            - name: Release The Build
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                 repo_token: "${{ secrets.GITHUB_TOKEN }}"
                 automatic_release_tag: "latest"
                 prerelease: false
                 title: "Release Build"
                 files: |
                  target/release/shticker_book_unwritten


    
