
  
name: Building Release Build
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Cross Compile
      run: |
       sudo apt-get install gcc-mingw-w64-x86-64 -y
       rustup target add x86_64-pc-windows-gnu
       
    - name: Building Windows Release
      run: cargo build --release --target x86_64-pc-windows-gnu
     
     

    - name: Building Linux Release
      run: cargo build --release
      
      
      
    - name: Release The Build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release Build"
          files: |
           /target/release/shticker_book_unwritten
           /target/x86_64-pc-windows-gnu/release/shticker_book_unwritten.exe

    
